services:
  - type: web
    name: ai-resume-enhancer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: UPLOAD_DIR
        value: /var/data/uploads
    disks:
      - name: uploads
        mountPath: /var/data/uploads
        sizeGB: 1
